name: check-formatting
on: [push, pull_request]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format.
      uses: jidicula/clang-format-action@v4.10.1
      with:
        clang-format-version: '15'
